import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider, useClerk } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main>
            <Header />
            {children}
          </main>

          {/* This is the one that lets the page refresh live with changes in sanity */}
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
